## 遇到的错误汇总

1. sqlalchemy.exc.UnboundExecutionError: Could not locate a bind configured on mapper mapped class Shop->shops or this Session

* 原因：  

- Session未和特定数据库绑定，所以sqlalchemy不知道应该修改那张表

* 解決方法：

用sessionmaker创建本地session，不直接用SQLAlchemy的db.session

Ref：[codegrepper.com](https://www.codegrepper.com/code-examples/python/Could+not+locate+a+bind+configured+on+mapper+mapped+class+class-%3Etablename%2C+SQL+expression+or+this+Session.)

2. Object xxx is already attached to session 'x' (this is 'x+1')

* 原因： 正在被修改的对象与不止一个db session存在附属关系，从而无法在当前被引用的db session当中修改

* 解决方法：
- 直接获取当前上下文中的db session，并在该session中修改对象(线程不安全)
```
current_sess = session.object_session(s)
current_sess.add(s)
```

- 将待修改的对象与当前上下文合并(线程安全)

```
object_to_modify_local = session.merge(object_to_modify)
session.add(object_to_modify_local)
```

Ref：[SQLAlchemy Object already attached to session](https://stackoverflow.com/questions/24291933/sqlalchemy-object-already-attached-to-session)

3. sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (2006, "Access denied for user 'root'@'localhost' (using password: YES)")   
(Background on this error at: http://sqlalche.me/e/e3q8)

在把解密后的密码添加到数据库URI后发生

Ref:[Python and Django OperationalError (2006, 'MySQL server has gone away')](https://www.py4u.net/discuss/787419#:~:text=Answer%20%232%3A%20Sometimes%20if%20you%20see%20%22OperationalError%3A%20%282006%2C,to%20put%20something%20really%20big%20in%20the%20session.)

4. 其他问题
   - 变量引用 
     - 名称不匹配
     - 在未被初始化前就引用 (对框架的内部处理机制不够了解)
     - 忘记在render_template()方法中向模板传递参数
   - 数据结构访问错误
     - 字典和列表未正确区分
     - 忘记给字典中的键赋值
   - 方法参数不匹配
   - 蓝本名和模板中引用的url不匹配